
version: '3'
services:
  postgres:
    image: postgres:16
    container_name: atlas-postgres
    restart: always

    environment:
      - POSTGRES_DB=atlas
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: '3'
    ports:
      - '5434:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./database/db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
